$ MASS Card
$#         IDNOD    IFRA   Blank            DISr            DISs            DISt
MASS  /        0       0                                                        
$#                                                                         TITLE
NAME MASS  / ->1                                                                
$# BLANK              Mx              My              Mz
                                                        
$# BLANK              Ix              Iy              Iz                   Blank
                                                                                
        END
