return {
MASS = {
  IDNOD = { "Node identification number.", "If set equal to 0, node entities are selected via keywords.", "integer (I8)", "0" },
  IFRA = { "Local frame identification number (type 1).", "", "integer (I8)", "0" },
  DISr = { "Distance component r from node IDNOD to COG.", "", "floating (E16)", "[length]" },
  DISs = { "Distance component s from node IDNOD to COG.", "", "floating (E16)", "[length]" },
  DISt = { "Distance component t from node IDNOD to COG.", "", "floating (E16)", "[length]" },
  TITLE = { "Added mass identification title.", "", "string (A76)", "" },
  Mx = { "Added nodal mass in X-direction.", "", "floating (E16)", "[mass]" },
  My = { "Added nodal mass in Y-direction.", "", "floating (E16)", "[mass]" },
  Mz = { "Added nodal mass in Z-direction.", "", "floating (E16)", "[mass]" },
  Ix = { "Added moment of inertia about X-axis.", "", "floating (E16)", "[mass].length^2" },
  Iy = { "Added moment of inertia about Y-axis.", "", "floating (E16)", "[mass].length^2" },
  Iz = { "Added moment of inertia about Z-axis.", "", "floating (E16)", "[mass].length^2" },
  Ixy = { "Added moment of inertia about XY-plane.", "", "floating (E16)", "[mass].length^2" },
  Iyz = { "Added moment of inertia about YZ-axis.", "", "floating (E16)", "[mass].length^2" },
  Ixz = { "Added moment of inertia about XZ-axis.", "", "floating (E16)", "[mass].length^2" },
},
CNODE = { 
  IDNOD = { "Common node identification number.", "", "integer (I8)", "0" },
  X = { "X coordinate of the nodal point.", "", "floating (E16)", "[length]" },
  Y = { "Y coordinate of the nodal point.", "", "floating (E16)", "[length]" },
  Z = { "Z coordinate of the nodal point.", "", "floating (E16)", "[length]" },
},
NODE = {
  IDNOD = { "Node identification number.", "", "integer (I8)", "0" },
  X = { "X coordinate of the nodal point.", "", "floating (E16)", "[length]" },
  Y = { "Y coordinate of the nodal point.", "", "floating (E16)", "[length]" },
  Z = { "Z coordinate of the nodal point.", "", "floating (E16)", "[length]" },
},
NSMAS2 = {
  IDNSM = { "Non-structural mass identification number.", "", "integer (I8)", "0" },
  MASS = { "Mass to be distributed on all selected part.", "", "floating (E16)", "[mass]" },
  MLEN = { "Mass per unit length to be distributed on 1D elements.", "", "floating (E16)", "[mass·length^-1]" },
  MARE = { "Mass per unit area to be distributed on 2D elements.", "", "floating (E16)", "[mass·length^-2]" },
  MVOL = { "Mass per unit volume to be distributed on 3D elements.", "", "floating (E16)", "[mass·length^-3]" },
  TITLE = { "Non-structural mass identification title.", "", "string (A76)", "" },
},
NSMAS = {
  IDNSM = { "Non-structural mass identification number.", "", "integer (I8)", "0" },
  MASS = { "Mass to be distributed on all selected part.", "", "floating (E16)", "[mass]" },
  MLEN = { "Mass per unit length to be distributed on 1D elements.", "", "floating (E16)", "[mass·length^-1]" },
  MARE = { "Mass per unit area to be distributed on 2D elements.", "", "floating (E16)", "[mass·length^-2]" },
  MVOL = { "Mass per unit volume to be distributed on 3D elements.", "", "floating (E16)", "[mass·length^-3]" },
  TITLE = { "Non-structural mass identification title.", "", "string (A76)", "" },
},
}
