[package]
authors = ["KillTheMule <KillTheMule@users.noreply.github.com"]
name = "nvimpam"
version = "0.0.1"

[dependencies]
log = "0.3.7"
simplelog = "0.4.2"
neovim-lib = { path = "neovim-lib" }

#[dependencies.neovim-lib]
#git = "https://github.com/daa84/neovim-lib.git"
#rev = "77bb54c8a07d10a389947e50127d0376ebfad5fa"
