[package]
authors = ["KillTheMule <KillTheMule@users.noreply.github.com"]
name = "nvimpam"
version = "0.0.1"

[dependencies]
log = "0.4.1"
simplelog = "0.5.1"
neovim-lib = "0.5.2"
failure = "0.1.1"

[lib]
name = "nvimpam_lib"
path = "src/lib.rs"

[profile.bench]
lto = true
debug = true
