[package]
authors = ["KillTheMule <KillTheMule@users.noreply.github.com"]
name = "nvimpam"
version = "0.0.1"

[dependencies]
log = "0.3.8"
simplelog = "0.4.2"
neovim-lib = "*"
failure = "*"

[lib]
name = "nvimpam_lib"
path = "src/lib.rs"

[profile.bench]
lto = true
debug = true
