$IMPMA Super Element Matrix Import
$#       IDIMPMAQUALIFY1QUALIFY2QUALIFY3  IMATYP    ISEL
IMPMA /        1                               0         
$#                                                                         TITLE
NAME IMPMA / ->1                                                                
$#                                                                       FNAMEma
                                                                                
