$FRAME IAXIS=0 U-based, 2 Vectors
$#          IFRA  IFRATY   IAXIS
FRAME /        1       0       0
$#                                                                         TITLE
NAME FRAME / ->1                                                                
$# BLANK              Ux              Uy              Uz
                      0.              0.              0.
$# BLANK              Vx              Vy              Vz   IDNOD
                      0.              0.              0.       0
