$FRAME IAXIS=2 T-based, 2 Vectors
$#          IFRA  IFRATY   IAXIS
FRAME /        1       0       2
$#                                                                         TITLE
NAME FRAME / ->1                                                                
$# BLANK              Tx              Ty              Tz
                      0.              0.              0.
$# BLANK              Ux              Uy              Uz   IDNOD
                      0.              0.              0.       0
