$FRICT Friction Model Type 12
$#        IDFRIC  IFROPT    VAL1    VAL2    VAL3    VAL4    VAL5    VAL6    VAL7
FRICT /        1      12                                                        
$#                                                                         TITLE
NAME FRICT / ->1                                                                
$#          VAL8    VAL9   VAL10   VAL11   VAL12   VAL13   VAL14   VAL15   VAL16
                                                                                
