$NLAVE - Non Local Averadge Definition
$#         IDNLV    TYPE
NLAVE /        1GLASS_EN
$#                                                                         TITLE
NAME Nlave->1                                                                   
$#      RADIUSav        ENERCRID SCALrad TIMcent TIMfail         LCscale
                                                        CURVE           
        END
