$RUPMO Type 0
$#        IDRUPT   IRUPT   IFMON  FILTER
RUPMO /        1       0                
$#                                                                         TITLE
NAME RUPMO / ->1                                                                
$# BLANK   FAILT   FAILD  AFAILN  AFAILS      A1      A2    INTF      D1      D2
              0.      0.      0.      0.      0.      0.       0                
