$RUPMO Type 2
$#        IDRUPT   IRUPT   IFMON  FILTER
RUPMO /        1       2                
$#                                                                         TITLE
NAME RUPMO / ->1                                                                
$# BLANK    USR1   FAILD    USR2    USR3    USR4    USR5    INTF      D1      D2
                      0.                                       0                
$# BLANK    USR6    USR7    USR8    USR9   USR10   USR11   USR12   USR13   USR14
                                                                                
$# BLANK   USR15   USR16   USR17   USR18   USR19   USR20   USR21   USR22   USR23
                                                                                
$# BLANK   USR24   USR25   USR26   USR27   USR28   USR29   USR30   USR31   USR32
                                                                                
