$RUPMO Type 3
$#        IDRUPT   IRUPT   IFMON
RUPMO /        1       3        
$#                                                                         TITLE
NAME RUPMO / ->1                                                                
$# BLANK    USR1    USR2    USR3    USR4    USR5    USR6    USR7    USR8    USR9
                                                                                
$# BLANK   USR10   USR11   USR12   USR13   USR14   USR15   USR16   USR17   USR18
                                                                                
