$RUPMO Type 5
$#        IDRUPT   IRUPT   IFMON  FILTER
RUPMO /        1       5                
$#                                                                         TITLE
NAME RUPMO / ->1                                                                
$# BLANK   FAILT   FAILD  AFAILN  AFAILS      A1      A2    INTF      D1      D2
              0.      0.      0.      0.      0.      0.       0                
$# BLANK  AFAILT  AFAILB      A3      A4
                                        
