$SENSOR Type 2
$#         ISENS    ITYP IREVFLG  ISOFST
SENSOR/        1       2                
$#                                                                         TITLE
NAME SENSOR/ ->1                                                                
$# BLANK    IACC    ISIG      VX      VY      VZ   IRESP  TARGET            NCYC
               0       0      0.      0.      0.       0      0.               0
