$SENSOR Type 8
$#         ISENS    ITYP IREVFLG
SENSOR/        1       8        
$#                                                                         TITLE
NAME SENSOR/ ->1                                                                
$# BLANK   IDBAG   IDCHA  IQUALI  TPRESS                                   BLANK
               0       0                                                        
