$ UDATA User Data
$#        IUDATA  IUDTYP           BLANK  CUDSEL   IDCUD           NUDTH
UDATA /        1                        CURVE          0                
$#                                                                         TITLE
NAME User Data->1                                                               
$# BLANK  CUDENT  IUDENT   IDENT
        NODE           0        
        END
