$ LINCO Linear Constraint
$#          IDLC  DOFTYP   NNODI
LINCO /        1                
$#                                                                         TITLE
NAME LINCO / ->1                                                                
$# BLANK  IDNODd   IDOFd   SFACd    IFRA
               0       1      0.       0
$# BLANK  IDNODi   IDOFi   SFACi   IFRAi
               0       1      0.       0
