$RBODY Type 1
$#          IDRB   BLANK    ITRBIDNODcog                   ISENS    IFRA     HRB
RBODY /        1               1       0                       0       0        
$#                                                                         TITLE
NAME RBODY / ->1                                                                
$# BLANK   TFAIL   FAILD  AFAILN  AFAILS      A1      A2    INTF      D1      D2
              0.      0.      0.      0.      0.      0.       0      0.      0.
        END
