$RBODY Type 2
$#          IDRB   BLANK    ITRBIDNODcog                   ISENS    IFRA     HRB
RBODY /        1               2       0                       0       0        
$#                                                                         TITLE
NAME RBODY / ->1                                                                
$# BLANK   TFAIL   FAILD  AFAILN  AFAILS      A1      A2    INTF
              0.      0.      0.      0.      0.      0.       0
        END
