$RBODY Type 3
$#          IDRB   BLANK    ITRBIDNODcog  IDNOD1  IDNOD2   ISENS    IFRA     HRB
RBODY /        1               3       0       0       0       0       0        
$#                                                                         TITLE
NAME RBODY / ->1                                                                
$# IT3FL     Mrb      I1      I2      I3   BLANK   BLANK   BLANK
              0.      0.      0.      0.                        
        END
