$MTOCO mit User Imposed Mass and Intertia
$#         IDMTO  IDNBLANKXYZUVW   IFRA1   ITMTO                  DOFTYP
MTOCO /        1       0  111111       0       1                        
$#                                                                         TITLE
NAME MTOCO / ->1                                                                
$# IT1FL    MMTO      I1      I2      I3   BLANK   BLANK   BLANK   IFRA2    NCOG
       0                                                               0       0
        END
