$  Material Type 1 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1       1              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat1                                                                    
$#       G    SIGMAy        Et     ALPHA     BLANK     BLANK    STRAT1    STRAT2
        0.CURVE             0.                                      0.        0.
$#       K   KEYWORD
        0.          
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  EPSLN1    EPSLN2    EPSLN3    EPSLN4    EPSLN5    EPSLN6    EPSLN7    EPSLN8
        0.        0.        0.        0.        0.        0.        0.        0.
$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$#  STRAT3    STRAT4    STRAT5    STRAT6        Q1        Q2        Q3
        0.        0.        0.        0.        0.        0.        0.
