$Material Type 100
MATER /        1     100              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat100                                                                  
$#       E     BLANK        NU     BLANK
        0.                  0.          
$blank

$blank

$blank

$blank

$blank

