$Material Type 101
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     101                       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat101                                                                  
$#       E     BLANK        NU     ALPHA       HGM       HGW       HGQ        As
                                                                                
$blank

$blank

$blank

$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$blank

