$Material Type 105 (CURVE Definition, HSR Damage)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     105              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat105                                                                  
$#       E    SIGMAy        NU     ALPHA       HGM       HGW       HGQ        As
        0.CURVE             0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#REL_THIN    STRAT1    STRAT2     EPSIi
                  0.        0.HSRDTYP   
$#EPSIpmax    IFelim    STRAT3    STRAT4    STRAT5    STRAT6       KSI        fo
        0.                  0.        0.        0.        0.        0.        0.
$# KEYWORD     VALUE  REL_THIC
                              
$# REL_HSR
          
