$Material Type 109 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     109              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat109                                                                  
$#       E    SIGMAy        NU       IYC       HGM       HGW       HGQ        As
        0.CURVE             0.         1                                        
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#EPSIpmax    STRAT1    STRAT2     RELIM                         BLANK     EPREF
        0.        0.        0.                                                  
$#  STRAT3    STRAT4    STRAT5    STRAT6     IDRUP     BLANK       KSI        Fo
        0.        0.        0.        0.         0                  0.        0.
$#   ALPHA      BETA     GAMMA     BLANK     BLANK     BLANK      HEXP     BLANK
        0.        0.        0.                                                  
$#   ELmn1     ELmj1     ELmn2     ELmj2     ELmn3     ELmj3     ELmn4     ELmj4
        0.        0.        0.        0.        0.        0.        0.        0.
