$ Material Type 11
#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      11              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat11                                                                   
$#       G        NU
        0.     0.463
$blank

$blank

$blank

$blank

$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
