$Material Type 110
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     110                       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat110                                                                  
$#   Eaust     Emart        NU     BLANK       HGM       HGW       HGQ        As
                                                                                
$#    BETA     ALPHACURVE           FNUM      RNUM
                    CURVE              0         0
$blank

$blank

$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$blank

