$Material Type 115  (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     115              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat115                                                                  
$#       E    SIGMAy        NU     BLANK       HGM       HGW       HGQ        As
        0.CURVE             0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#REL_THIN    STRAT1    STRAT2        q1        q2        Fi        Fc        Ff
                  0.        0.        0.        0.        0.        0.        0.
$#             BLANK    STRAT3    STRAT4    STRAT5    STRAT6       KSI        Fo
                            0.        0.        0.        0.        0.        0.
$#      Fn        Sn     EPSIn        Tn   KEYWORD     VALUE  REL_THIC     BLANK
        0.        0.        0.        0.                                        
