$Material Type 117 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     117              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat117                                                                  
$#       E    SIGMAy        NU     BLANK       HGM       HGW       HGQ        As
        0.CURVE             0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#EPSIpmax    STRAT1    STRAT2     RELIM       AKC     QLANK       IYC     EPREF
        0.        0.        0.                                       0          
$#  STRAT3    STRAT4    STRAT5    STRAT6     IDRUP     BLANK       KSI        Fo
        0.        0.        0.        0.         0                  0.        0.
$#       G         F         N   PORTHO1   PORTHO2   PORTHO3     IGOYA    NASSPL
        0.        0.        0.                                                  
$#   ELmn1     ELmj1     ELmn2     ELmj2     ELmn3     ELmj3     ELmn4     ELmj4
        0.        0.        0.        0.        0.        0.        0.        0.
