$ Material Type 12
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      12              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat12                                                                   
$#       G        CA        CB        CN        CC        CM
        0.                                                  
$#   Tmelt    EPSLNo         C      Pcut               BLANK   MIN_VOL   MAX_VOL
                                                                                
$#      C0        C1        C2        C3        C4        C5        C6
                                                                      
$#   Troom                                   BLANK FRAC_ELIM    VFELIM     TELIM
                                                                                
$#   EPMAX        EI        EL        D1        EU        DU       KSI        fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
