$Material Type 121
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     121              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat121                                                                  
$#       E     BLANK        NU     ALPHA       HGM       HGW       HGQ        As
        0.                  0.                                                  
$#bKW              k         m        h1        h2         w
CONST                                                       
$# TIMEfil  ERATEref
                  1.
$#EPSIpmax     BLANK     BLANK  REL_THIN EPSIppmax  REL_THIC
                                                            
$blank

$blank

$blank

