$Material Type 126
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     126                       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat126                                                                  
$#       E     BLANK        NU     ALPHA       HGM       HGW       HGQ        As
                                                                                


$#  SIGMAc   TIMEfil  LCsigmac QUALIFIER   LCscale
                                                  
$#   IELIM       ICC                                   BLANK       KSI        Fo
                                                                    0.        0.
$blank

