$Material Type 127 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     127              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat127                                                                  
$#       E   SIGMA_Y       NUE     BLANK       HGM       HGW       HGQ        As
        0.CURVE             0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#  STRAT1    STRAT2    STRAT3    STRAT4    STRAT5    STRAT6
        0.        0.        0.        0.        0.        0.
$#     IYC         G         F         N         L         M
                                                            
$#     KSI        f0     RELIM        LC        Ks     IFAIL     IKINH
                                                                     0
$# IFUN1nf   IFUN2nf   IFUN3nf   IFUN4nf   IFUN5nf   IFUN6nf   IFUN7nf   IFUN8nf
         0         0         0         0         0         0         0         0
$#ERATE1nf  ERATE2nf  ERATE3nf  ERATE4nf  ERATE5nf  ERATE6nf  ERATE7nf  ERATE8nf
                                                                                
$# IFUN1sf   IFUN2sf   IFUN3sf   IFUN4sf   IFUN5sf   IFUN6sf   IFUN7sf   IFUN8sf
         0         0         0         0         0         0         0         0
$#ERATE1sf  ERATE2sf  ERATE3sf  ERATE4sf  ERATE5sf  ERATE6sf  ERATE7sf  ERATE8sf
                                                                                
$# IFUNFLD   IFUNMSO  IFILTMSO   SFACMSO
         0         0                    
