$Material Type 128
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     128              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat128                                                                  
$#       E    SIGMAy        NU     BLANK       HGM       HGW       HGQ        As
        0.CURVE             0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#   BLANK    STRAT1    STRAT2      RELM     BLANK        Lc
                  0.        0.                              
$#  STRAT3    STRAT4    STRAT5    STRAT6      NFIL      DEPS       KSI        Fo
        0.        0.        0.        0.                            0.        0.
$#     IYC                                       m                         BLANK
                                                                                
$#  EPSNos        ns        ms    EPSIod        nd        md  ERATEref
                                                                      
$#      R0       R45       R90       KH1       KH2       KH3         D
                                                                      
$#   FLDS1     FLDS2     FLDS3     FLDS4     FLDD1     FLDD2     FLDD3     FLDD4
                                                                                
$#    DFS1      DFS2      DFS3      DFD1      DFD2      DFD3      DFA1      DFA2
                                                                                
$#    SFS1      SFS2      SFS3      SFD1      SFD2      SFD3       SFK
                                                                      
