$Material Type 132
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     132              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat130                                                                  
$#     KSI        FoNOPER ILAY                 HGM       HGW       HGQ        As
        0.        0.    1    0                                                  
$#   IDPLY     THKPL     ANGPL
         0        0.        0.
$#   BLANK NMINBLANK   GRUC_KW  GRUC_VALIFAILBLANK    ERATIO               BLANK
              0                             0                                   
$#PLIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUX8
                                                                                
$#PLIDAUIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUX16
                                                                                
$#PIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUX24
                                                                                
$#PIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUX32
                                                                                
$#PIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUX40
                                                                                
$#PIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUXIDPLYIDAUX48
                                                                                
