$Material Type 143
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     143              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat143                                                                  
$#   BLANK                  NU     ALPHA       HGM       HGW       HGQ        As
                            0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#EPSItmax    STRAT1    STRAT2  REL_THIN  REL_THIC     Lcmax     IFAIL    IFelim
        0.        0.        0.                             0         0          
$#             BLANK    STRAT3    STRAT4    STRAT5    STRAT6       KSI        Fo
                            0.        0.        0.        0.        0.        0.
$# KEYWORD     VALUE                                                       BLANK
                                                                                
