$ Material Type 15
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      15              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat15                                                                   
$#       G                                             BLANK       KSI        Fo
        0.                                                          0.        0.
$#       K        C0        C1        C2        C3
        0.                                        
$#  Ftprim     Kpost
                    
$#  Fcprim        A0        A1        A2        B0        B1        B2     EPSIp
                                                                                
$#       E        NU    SIGMAy    RATIOr    RATIOs    RATIOt        Ep      IDIR
        0.        0.                                                            
$#   FRLIM     EPLIM     DSMIN                  Q1        Q2        Q3
                                                0.        0.        0.
