$Marerial Type 150
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     150              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat150                                                                  
$#       E        NU     BLANK  EPSIclim    AREDUC                 KSI    IFLA90
        0.        0.              -0.375      0.01                  0.         0
$#

$#

$blank

$# IMATLAW    LCLEAK
         0         0
$#    SVWL      SVWR     SVWC1     SVWC2     SVWC3    SVWDIS
                                                            
