$Material Type 151
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     151              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat151                                                                  
$#   BLANK    LAMBDA    AREDUC       Goh   PSIlock       G1h          IHARDIHYST
                  0.      0.01  0.000000                                  0    0
$# LCload1     BLANK        H1        D1    EPSI10                         BLANK
         0                  0.        0.        0.                              
$# LCload2     BLANK        H2        D2    EPSI20                         BLANK
         0                  0.        0.        0.                              
$blank

$#  LCLEAK    LCSTRS    LCRAT1    LCRAT2     EPSIi     EPSIu        Ko
         0         0         0         0        0.        0.        0.
$#    SVWL      SVWR     SVWC1     SVWC2     SVWC3    SVWDIS
                                                            
