$Material Type 152
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     152              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat152                                                                  
$#   BLANK    LAMBDA    AREDUC                                             BLANK
                  0.      0.01                                                  
$#       E        Fg               BLANK IWR1        Ao        Bo     DELTABLANK
                                                                                
$#   NKLAY                                                                 BLANK
                                                                                
$blank

$#   BLANK    LCLEAK
                   0
$blank

