$ Material Type 16 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      16              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat16                                                                   
$#       G    SIGMAy        Et     ALPHA       IYC     BLANK    STRAT1    STRAT2
        0.CURVE             0.                                      0.        0.
$#       K     IDRUP       YC1       YC2       YC3       YC4       YC5       YC6
        0.         0                                                            
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  EPSLN1    EPSLN2    EPSLN3    EPSLN4    EPSLN5    EPSLN6    EPSLN7    EPSLN8
        0.        0.        0.        0.        0.        0.        0.        0.
$#EPSLNMAX     EPSIi     EPSI1        d1     EPSIu        du       KSI        Fo
        0.        0.        0.        0.        0.        0.        0.        0.
$#  STRAT3    STRAT4    STRAT5    STRAT6        Q1        Q2        Q3     PFRAC
        0.        0.        0.        0.        0.        0.        0.          
