$Material Type 161
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     161                       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat161                                                                  
$#       E     BLANK        NU                                   BLANK        As
                                                                                
$#   IFLAW                                                                 BLANK
                                                                                
$blank

$blank

$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$blank

