$ Material Type 17
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      17              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat17                                                                   
$#   Aload     Bload    NUload      Aunl      Bunl     NUunl
        0.        0.      0.49        0.        0.        0.
$# LTCload    LTCunl   NSEARCH    NDECAY
         0         0         0         0
$blank

$blank

$blank

$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
