$Material Type 171 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     171              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat171                                                                  
$#       E    SIGMAy        NU     ALPHA       HGM       HGW       HGQ        As
        0.CURVE             0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#   BLANK    STRAT1    STRAT2     DEWKi     DEWK1        d1     DEWKu        du
                  0.        0.                                                  
$# SECelim     BLANK    STRAT3    STRAT4    STRAT5    STRAT6       KSI        Fo
                            0.        0.        0.        0.        0.        0.
$#       H        Dc        Rc      Plim   ALPHA_P      BETA       IW1
                  0.                                                  
