$ Material Type 18
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      18              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat18                                                                   
$#       A         B         C         D       NUE
        0.        0.        0.        0.      0.49
$blank

$blank

$blank

$blank

$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
