$ Material Type 19
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      19              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat19                                                                   
$#    Ainf      Binf        NU
        0.        0.      0.49
$#      A1        B1      TAU1        A2        B2      TAU2
        0.        0.        0.        0.        0.        0.
$blank

$blank

$blank

$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
