$  Material Type 2
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1       2              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat2                                                                    
$#       G        K0        a0        a1        a2       Pfr    STRAT1    STRAT2
        0.        0.        0.        0.        0.        0.        0.        0.
$#  EPSIv1        P1    EPSIv2        P2        Q1        Q2        Q3
        0.        0.        0.        0.        0.        0.        0.
$#  EPSIv3        P3    EPSIv4        P4
        0.        0.        0.        0.
$#  EPSIv5        P5    EPSIv6        P6
        0.        0.        0.        0.
$#  EPSIv7        P7    EPSIv8        P8     BLANK                 KSI        Fo
        0.        0.        0.        0.                            0.        0.
$#  EPSIv9        P9   EPSIv10       P10    STRAT3    STRAT4    STRAT5    STRAT6
        0.        0.        0.        0.        0.        0.        0.        0.
