$ Material Type 20
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      20              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat20                                                                   
$#       E         A         B         C        p0       PHI     BLANK     BLANK
        0.        0.        0.        0.        0.        0.                    
$blank

$blank

$blank

$#                                                     BLANK       KSI        fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
