$Material Type 200
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     200              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat200                                                                  
$#       E                                                                 BLANK
        0.                                                                      
$blank

$blank

$blank

$blank

$blank

