$Material Type 201
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     201                       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat201                                                                  
$#       E        NU                         ALPHA
                                                  

$#    KSIm      KSIb      KSIt
                  0.        0.
$blank

$blank

$blank

