$Material Type 203
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     203              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat203                                                                  
$#      Eo     BLANK   DLelimc   DLelimt     BLANK   DLelast   DLelasc
        0.                  0.        0.                  0.        0.
$#   BLANKNMAINNUNLDNRELD
              0    0    0
$#  DELTA1        F1    DELTA2        F2    DELTA3        F3    DELTA4        F4
        0.        0.        0.        0.        0.        0.        0.        0.

$# DLTunl1     Funl1   DLTunl2     Funl2   DLTunl3     Funl3   DLTunl4     Funl4
        0.        0.        0.        0.        0.        0.        0.        0.
$# DLTrel1     Frel1   DLTrel2     Frel2   DLTrel3     Frel3   DLTrel4     Frel4
        0.        0.        0.        0.        0.        0.        0.        0.
