$Material Type 204
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     204              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat204                                                                  
$#   NLOAD   CMULTloIHYST
         0        1.    0
$#   NUNLD   UNLCMUL     NDAMP   DAMPMUL     NMULT     BLANK
         0        1.         0        1.         0          
$#       K         C     DLini
        0.        0.        0.
$#MASSsprg        Ko
        0.        0.
$#      Ft        Fc   DLelimt   DLelimc
        0.        0.        0.        0.
$blank

