$Material Type 205
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     205              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat205                                                                  
$#   NLOADIHYST
         0    0
$#       H         D     BLANK     BLANK
        0.        0.                    
$#  K_dash       KSI     EPSI0
                  0.        0.
$#      MU        Ko
                    
$#   EPSIi     EPSIu
        0.        0.
$blank

