$ Material Type 21
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      21              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat21                                                                   
$#       E  SIGMAcut     ALPHA      BETA   EPSIlim  ICU         C     BLANKICURV
        0.        0.        1.                        0        0.              0
$#   EPSI1     EPSI2     EPSI3     EPSI4     EPSI5     EPSI6     EPSI7     EPSI8
        0.        0.        0.        0.        0.        0.        0.        0.
$#  SIGMA1    SIGMA2    SIGMA3    SIGMA4    SIGMA5    SIGMA6    SIGMA7    SIGMA8
        0.        0.        0.        0.        0.        0.        0.        0.
$#   EPSI9    EPSI10    EPSI11    EPSI12    EPSI13    EPSI14    EPSI15    EPSI16
        0.        0.        0.        0.        0.        0.        0.        0.
$#  SIGMA9   SIGMA10   SIGMA11   SIGMA12   SIGMA13   SIGMA14   SIGMA15   SIGMA16
        0.        0.        0.        0.        0.        0.        0.        0.
$#  STRAT1    STRAT2  KSILMBx0LMBY0LMBZ0        Q1        Q2        Q3        Fo
        0.        0.   0.   0.   0.   0.        0.        0.        0.        0.
