$Material Type 212 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     212              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat212                                                                  
$#       E       NUE    SIGMAy        Et     ALPHA
        0.        0.CURVE             0.          

$#    KSIm      KSIb      KSIt
        0.        0.        0.
$#EPSIpmax    STRAT1    STRAT2    STRAT3    STRAT4    STRAT5    STRISTRelim
        0.        0.        0.        0.        0.        0.        0.     
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
