$Material Type 214
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     214              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat214                                                                  
$#       E        NU      LCMs    SCFACs      LCMt    SCFACtITYPM
        0.        0.         0        1.         0        1.    0
$blank

$#    KSIm      KSIb      KSIt
        0.        0.        0.
$blank

$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#   Mend1     Mend2     Mend3     Mend4     Mend5     Mend6     Mend7     Mend8
        0.        0.        0.        0.        0.        0.        0.        0.
