$Material Type 22
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      22              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat22                                                                   
$#     E10  YOUNGexp     ETA20       E20   VISCexp     BLANK     BLANK     BLANK
        0.        0.        0.        0.        0.                              
$#      NU                                                                 BLANK
        0.                                                                      



$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
