$Material Type 220
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     220              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat220                                                                  
$#  NLOADr      FTLr IHtr    RUPLtr    RUPUtr                             WDMPtr
         0        1.    1                                                       
$#  NUNLDr      FTUr     MASSr    NDAMPr      FTDr    SLOPtr    DLelar       Ktr
         0        1.        0.         0        1.        0.        0.          
$#  NLOADs      FTLs IHts    RUPLts    RUPUts                             WDMPts
         0        1.    1                                                       
$#  NUNLDs      FTUs     MASSs    NDAMPs      FTDs    SLOPts    Dlelas       Kts
         0        1.        0.         0        1.        0.        0.          
$#  NLOADt      FTLt IHtt    RUPLtt    RUPUtt                             WDMPtt
         0        1.    1                                                       
$#  NUNLDt      FTUt     MASSt    NDAMPt      FTDt    SLOPtt    Dlelat       Ktt
         0        1.        0.         0        1.        0.        0.          
$#  MLOADr      FMLr IHrr    RUPLrr    RUPUrr                             WDMPrr
         0        1.    1                                                       
$#  MUNLDr      FMUr     INERr    MDAMPr      FMDr    SLOPrr    Rtelar       Krr
         0        1.        0.         0        1.        0.        0.          
$#  MLOADs      FMLs IHrs    RUPLrs    RUPUrs                             WDMPrs
         0        1.    1                                                       
$#  MUNLDs      FMUs     INERs    MDAMPs      FMDs    SLOPrs    RTelas       Krs
         0        1.        0.         0        1.        0.        0.          
$#  MLOADt      FMLt IHrt    RUPLrt    RUPUrt                             WDMPrt
         0        1.    1                                                       
$#  MUNLDt      FMUt     INERt    MDAMPt      FMDt    SLOPrt    Rtelat       Krt
         0        1.        0.         0        1.        0.        0.          
