$Material Type 221
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     221              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat221                                                                  
$#  MLOADr      FMLr IHrr
         0        1.    0
$#  MUNLDr      FMUr      Cphi    Mrelas     BLANK
         0        1.        0.        0.          
$#  MLOADs      FMLs IHrs
         0        1.    0
$#  MUNLDs      FMUs    Ctheta    Mselas     BLANK
         0        1.        0.        0.          
$#  MLOADt      FMLt Ihrt
         0        1.    0
$#  MUNLDt      FMUt      Cpsi    Mtelas     BLANK
         0        1.        0.        0.          
$#   MUphi   Mutheta     MUpsi  OMEGAini  OMEGAfin
        0.        0.        0.        0.        0.
$#  Ktrans  TOLtrans DAMPtrans
        0.        0.        0.
