$Material Type 222
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     222              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat222                                                                  
$#  MLOADu      FMLu IHru
         0        1.    0
$#  MUNLDu      FMUu    Calpha    Muelas     BLANK
         0        1.        0.        0.          
$#    MDIR      FDIR
         0        0.
$#  MLOADt      FMLt Ihrt
         0        1.    0
$#  MUNLDt      FMUt     Cbeta    Mtelas     BLANK
         0        1.        0.        0.          
$# MUalpha    MUbeta  OMEGAini  OMEGAfni
        0.        0.        0.        0.
$#  Ktrans  TOLtrans DAMPtrans
                              
