$Material Type 223
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     223              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat223                                                                  
$#  NLOADr      FTLr IHtr    RUPLtr    RUPUtr    NMFDTr    DLinirINDOF     IDRUP
         0        1.    1                             0                        0
$#  NUNLDr      FTUr     MASSr    NDAMPr      FTDr    SLOPtr    DLelar
         0        1.        0.         0        1.        0.        0.
$#  NLOADs      FTLs IHts    RUPLts    RUPUts    NMFDTs    DLinis          ILENG
         0        1.    1                             0                         
$#  NUNLDs      FTUs     MASSs    NDAMPs      FTDs    SLOPts    DLelas
         0        1.        0.         0        1.        0.        0.
$#  NLOADt      FTLt IHtt    RUPLtt    RUPUtt     NMFDt    DLinit
         0        1.    1                             0          
$#  NUNLDt      FTUt     MASSt    NDAMPt      FTDt    SLOPtt    DLelat
         0        1.        0.         0        1.        0.        0.
$#  MLOADr      FMLr IHrr    RUPLrr    RUPUrr    NMMDTr    RTinir
         0        1.    1                             0          
$#  MUNLDr      FMUr     INERr    MDAMPr      FMDr    SLOPrr    RTelar
         0        1.        0.         0        1.        0.        0.
$#  MLOADs      FMLs IHrs    RUPLrs    RUPUrs    NMMDTs    RTinis
         0        1.    1                             0          
$#  MUNLDs      FMUs     INERs    MDAMPs      FMDs    SLOPrs    RTelas
         0        1.        0.         0        1.        0.        0.
$#  MLOADt      FMLt IHrt    RUPLrt    RUPUrt    NMMDTt    RTinit
         0        1.    1                             0          
$#  MUNLDt      FMUt     INERt    MDAMPt      FMDt    SLOPrt    RTelat
         0        1.        0.         0        1.        0.        0.
