$Material Type 224
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     224              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat224                                                                  
$# SLFACMt   SLFACMr       KSI     XMASS   INERTIA     INDOF     IDRUP     IFLGP
                            0.                                       0          
$blank

$blank

$blank

$blank

$blank

