$Material Type 225
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     225              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat225                                                                  
$#  KWFL       MASSt     MASSr    Ktrans      Krot   SLPMULT
CURVE                                                       
$#NLOADUPr  NLOADLWr    NDAMPr
         0         0         0
$#NLOADUPs  NLOADLWs    NDAMPs
         0         0         0
$#NLOADUPt  NLOADLWt    NDAMPt
         0         0         0
$#MLOADUPr  MLOADLWr    MDAMPr
         0         0         0
$#MLOADUPs  MLOADLWs    MDAMPs
         0         0         0
$#MLOADUPt  MLOADLWt    MDAMPt
         0         0         0
$#   TTTR3     RRRR3
       000       000
