$Material Type 226
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     226              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat226                                                                  
$#    IDVU      IDAU        Vz  ICHANNEL     ALPHA
         0         0        0.         0        0.
$#      Cp        P0        T0        F1        U1       Kam      Kamz
        0.        0.        0.        0.        0.        0.        0.
$blank

$blank

$blank

$blank

