$Material Type 230
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     230              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat230                                                                  
$# NLOADr1   FFRICr1    Vinir1    Vfinr1IHtr1
         0        0.        0.        0.    0
$# NUNLDr1    SLOPr1   NDAMPr1   DLelar1
         0        0.         0        0.
$# NLOADs1   FFRICs1    Vinis1    Vfins1IHts1
         0        0.        0.        0.    0
$# NUNLDs1    SLOPs1   NDAMPs1   DLelas1
         0        0.         0        0.
$# NLOADt1   FFRICt1    Vinit1    Vfint1 IHt1
         0        0.        0.        0.    0
$# NUNLDt1    SLOPt1   NDAMPt1   DLelat1
         0        0.         0        0.
$#LOADtet1 MFRICtet1OMGinitet1OMGfintetIHtet1
         0        0.        0.        0.    0
$#UNLDtet1  SLOPtet1 MDAMPtet1 RTelatet1
         0        0.         0        0.
$#LOADtet2 MFRICtet2OMGinitet2OMGfintetIHtet2
         0        0.        0.        0.    0
$#UNLDtet2  SLOPtet2 MDAMPtet2 RTelatet2
         0        0.         0        0.
$#LOADtet3 MFRICtet3OMGinitet3OMGfintetIHtet3
         0        0.        0.        0.    0
$#UNLDtet3  SLOPtet3 MDAMPtet3 RTelatet3
         0        0.         0        0.
