$ Material Type 24
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      24              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat24                                                                   
$#      Ec        Et        po       PHI   EPSLNel      PLIM               BLANK
                                                                                
$#   NCRV1     NCRV2     NCRV3     BLANK     BLANK     BLANK     BLANK     BLANK
         0         0         0                                                  
$blank

$blank

$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$#  STRAT1    STRAT2               BLANK        Q1        Q2        Q3
        0.        0.                            0.        0.        0.
