$ Material Type 25
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      25              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat25                                                                   
$#       E         A         B         C        Po       PHI     BLANK     BLANK
        0.        0.        0.        0.        0.        0.                    
$#  EPSIv1    EPSIv2    EPSIv3    EPSIv4    EPSIv5    EPSIv6    EPSIv7    EPSIv8
        0.        0.        0.        0.        0.        0.        0.        0.
$#    SSF1      SSF2      SSF3      SSF4      SSF5      SSF6      SSF7      SSF8
        0.        0.        0.        0.        0.        0.        0.        0.
$#   BLANK    STRAT1    STRAT2
                  0.        0.
$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
