$ Material Type 26 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      26              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat26                                                                   
$#       G    SIGMAy        Et       KSI        Fo     BLANK    STRAT1    STRAT2
        0.CURVE             0.        0.        0.                  0.        0.
$#       K
        0.
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#      q1        q2        fi        fn        Sn     EPSIn        fc        fF
        0.        0.        0.        0.        0.        0.        0.        0.
$#  STRAT3    STRAT4    STRAT5    STRAT6        Q1        Q2        Q3
        0.        0.        0.        0.        0.        0.        0.
