$ Material Type 28
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      28              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat28                                                                   
$#       B     GAMMA                                                       BLANK
        0.        0.                                                            
$#      P0   Pcutoff
                    
$blank

$blank

$blank

$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
