$ Material Type 30
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      30              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat30                                                                   
$#   IDPLY      ILAY
         0          
$#EPSIslim NMIN                         IFAIL
        0.    0                              
$blank

$blank

$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
