$Material Type 301
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     301              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat301                                                                  
$#    KSIt    SLFACM     FSNVL    DELTNL   IDEABEN      KSIr     BLANK    TLSTIF
        0.                                                                      
$#    IDOF     ITENS     IDRUP    DDDOFU    DSTART    DRELEA      RFAC
                             0                                        
$blank

$blank

$blank

$blank

