$Material Type 302
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     302              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat302                                                                  
$#  SLFACM     FSNVL    DELTNL                         IFLGC     BLANK    TLSTIF
                                                                                
$#   I3DOF    TOLCOR     IDRUP
                             0
$blank

$blank

$blank

$blank

