$Material Type 303
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     303              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat303                                                                  
$#     KSI    SLFACm               BLANK   IDEABEN  IDELBEND   DAMRATE    TLSTIF
        0.                                                                      
$#    IDOF     IDELA
                    
$#   hcont        E0        G0    STRAT1    STRAT2     Nfilt
                                      0.        0.          
$# SIGMApr   GAMMApr    EFRAC1    EFRAC2   SIGMAst   GAMMAst               NFEQD
                                                                                
$#  Ncycle IFUNGcont
                   0
$blank

