$Material Type 304
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     304              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat304                                                                  
$#     KSI     hcont     BLANK    STRAT1    STRAT2     Nfilt   IDEABEN
        0.                            0.        0.                    
$#   EC_NN  EC_NNopt                                   BLANK   CELC_NN
                                                                      
$#   ET_NN  ET_NNopt                                   BLANK   CELT_NN
                                                                      
$#    G_NT   G_NTopt                                   BLANK    CEL_NT
                                                                      
$#    G_NU   G_NUopt                                   BLANK    CEL_NU
                                                                      
$#   LKC_N     INC_N    INC_NT    INC_NU
         0                              
$#   LKT_N     INT_N    INT_NT    INT_NU
         0                              
$#   LK_NT     ITN_N    ITN_NT    ITN_NU
         0                              
$#   LK_NU     ITN_N    ITN_NT    ITN_NU
         0                              
