$Material Type 305
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     305              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat305                                                                  
$#     KSI    IELAST     IDELA       ETA    Ncycle     NFEQD     IELIM     IDRUP
        0.                                                                     0
$#  PSLOPE     RSURF
                    
$#      En     SIGSn   R_SIGSn     SIGDn   R_SIGDn     EFRSn   R_EFRSn     EFRDn
                                                                                
$# R_EFRDn       PCn
                    
$#      Es     SIGSs   R_SIGSs     SIGDs   R_SIGDs     EFRSs   R_EFRSs     EFRDs
                                                                                
$# R_EFRDs       PCs
                    
