$ Material Type 31
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      31              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat31                                                                   
$#   IDPLY                                             BLANK       KSI        Fo
         0                                                          0.        0.
$#EPSIslim  EPSIflim NMINNMAINNUNLDNRELD        Q1        Q2        Q3
        0.        0.    0    0    0    0        0.        0.        0.
$#   EPSI1    SIGMA1     EPSI2    SIGMA2     EPSI3    SIGMA3     EPSI4    SIGMA4
        0.        0.        0.        0.        0.        0.        0.        0.

$#  EPSIu1     SIGu1    EPSIu2     SIGu2    EPSIu3     SIGu3    EPSIu4     SIGu4
        0.        0.        0.        0.        0.        0.        0.        0.
$#  EPSIr1     SIGr1    EPSIr2     SIGr2    EPSIr3     SIGr3    EPSIr4     SIGr4
        0.        0.        0.        0.        0.        0.        0.        0.
