$ Material Type 37
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      37              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat37                                                                   
$#      NU         N         M     ALPHA             LTCsoft        Gd    SIGMAy
        0.                                                 0                    
$#     MU1       MU2       MU3       MU4       MU5       MU6       MU7       MU8
                                                                                
$#  ALPHA1    ALPHA2    ALPHA3    ALPHA4    ALPHA5    ALPHA6    ALPHA7    ALPHA8
                                                                                
$#      G1        G2        G3        G4        G5        G6        G7        G8
                                                                                
$#    TAU1      TAU2      TAU3      TAU4      TAU5      TAU6      TAU7      TAU8
                                                                                
$#LTCuniax   LTCbiax LTCpshear    LTCvol        Q1        Q2        Q3       KSI
         0         0         0         0        0.        0.        0.          
