$Material Type 371
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1     371              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat371                                                                  
$#                                         IDEABEN
                                                  
$#    IDOF     ITENS     IDRUP       COD    DSTART    DRELEA      RFAC
                             0       000                              
$blank

$blank

$blank

$blank

