$ Material Type 38
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      38              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat38                                                                   
$#      NU         N         M        Nv        Mv   LTCsoft        Gd      Sigy
        0.         0         0         0         0         0                    
$#     Mu1       Mu2       Mu3       Mu4       Mu5       Mu6       Mu7       Mu8
                                                                                
$#  ALPHA1    ALPHA2    ALPHA3    ALPHA4    ALPHA5    ALPHA6    ALPHA7    ALPHA8
                                                                                
$#  GAMMA1    GAMMA2    GAMMA3    GAMMA4    GAMMA5    GAMMA6    GAMMA7    GAMMA8
                                                                                
$#    TAU1      TAU2      TAU3      TAU4      TAU5      TAU6      TAU7      TAU8
                                                                                
$#LTCuniax   LTCbiax  LTCshear    LTCvol        Q1        Q2        Q3     ALPHA
         0         0         0         0        0.        0.        0.          
$#      D1        D2        D3        D4        D5        D6        D7        D8
                                                                                
$#   BETA1     BETA2     BETA3     BETA4     BETA5     BETA6     BETA7     BETA8
                                                                                
$#   TAUv1     TAUv2     TAUv3     TAUv4     TAUv5     TAUv6     TAUv7     TAUv8
                                                                                
$#LTCshrel LTCvolrel                                   BLANK
         0         0                                        
