$ Material Type 41
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      41              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat41                                                                   
$#     EoT    EPSIyT       E1T       E2T      GoTL   EPSIyTL      G1TL   SIGMAyT
        0.        0.        0.        0.        0.        0.        0.        0.
$#     EoL    EPSIyL       E1L       E2L      GoLW   EPSIyLW      G1LW   SIGMAyL
        0.        0.        0.        0.        0.        0.        0.        0.
$#     EoW    EPSIyW       E1W       E2W      GoWT   EPSIyWT      G1WT   SIGMAyW
        0.        0.        0.        0.        0.        0.        0.        0.
$#   EPSIc                                             BLANK
        0.                                                  
$#      D1        DU     EPSIi     EPSI1     EPSIu    STRAT1    STRAT2
        0.        0.        0.        0.        0.        0.        0.
$#   ALPHA  EPSIdoff  EPSIdten  EPSIelim        Q1        Q2        Q3
        0.        0.        0.        0.        0.        0.        0.
