$ Material Type 42
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      42              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat42                                                                   
$#   EC_TT     AC_TT   ICUC_TT             ASIC_TT   ESIC_TT   ALIC_TT   ELIC_TT
                             0                                                  
$#   ET_TT     AT_TT   ICUT_TT             ASIT_TT   ESIT_TT   ALIT_TT   ELIT_TT
        0.                   0                                                  
$#   EC_LL     AC_LL   ICUC_LL             ASIC_LL   ESIC_LL   ALIC_LL   ELIC_LL
                             0                                                  
$#   ET_LL     AT_LL   ICUT_LL             ASIT_LL   ESIT_LL   ALIT_LL   ELIT_LL
        0.                   0                                                  
$#   EC_WW     AC_WW   ICUC_WW             ASIC_WW   ESIC_WW   ALIC_WW   ELIC_WW
                             0                                                  
$#   ET_WW     AT_WW   ICUT_WW             ASIT_WW   ESIT_WW   ALIT_WW   ELIT_WW
        0.                   0                                                  
$#    G_TL      A_TL    ICU_TL              ASI_TL    ESI_TL    ALI_TL    ELI_TL
        0.                   0                                                  
$#    G_LW      A_LW    ICU_LW              ASI_LW    ESI_LW    ALI_LW    ELI_LW
        0.                   0                                                  
$#    G_TW      A_TW    ICU_TW              ASI_TW    ESI_TW    ALI_TW    ELI_TW
                             0                                                  
$#                      STRAT1    STRAT2        Q1        Q2        Q3  STRATFAC
                            0.        0.        0.        0.        0.          
$#   EVOLC     EVOLT     EVOMC     EVOMT     EVSLC     EVSLT     EVSMC     EVSMT
                                                                                
$#    Eswi     NUswi       LCy     Lcdam      Iswi      Aswi
                             0         0                    
