$ Material Type 45
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      45              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat45                                                                   
$#       E    UNLFAC     HYDRO       KSI    SLMULT        Fo    XRATUL   IRATEXT
        0.                  0.        0.        0.        0.        0.          
$#    LCc1      LCc2      LCc3      LCc4      LCc5      LCc6      LCc7      LCc8
         0         0         0         0         0         0         0         0
$#  ERATc1    ERATc2    ERATc3    ERATc4    ERATc5    ERATc6    ERATc7    ERATc8
        0.        0.        0.        0.        0.        0.        0.        0.
$#    LCt1      LCt2      LCt3      LCt4      LCt5      LCt6      LCt7      LCt8
         0         0         0         0         0         0         0         0
$#  ERATt1    ERATt2    ERATt3    ERATt4    ERATt5    ERATt6    ERATt7    ERATt8
        0.        0.        0.        0.        0.        0.        0.        0.
$#  LCC_ul    LCT_ul     ALPHA     BLANK        Q1        Q2        Q3     IFLAG
         0         0                            0.        0.        0.          
