$ Material Type 47
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      47              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat47                                                                   
$#               LCC    LCcunl       LCT    LCtunl
    STATIC         0         0         0         0
$blank

$blank

$#             ISENS
   DYNAMIC         0
$# IFUNDYN
         0
$#IFUNDAMP
         0
