$  Material Type 5
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1       5              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat5                                                                    
$#       K        G0      GINF      BETA     ALPHA
        0.        0.        0.        0.          



$#                                                     BLANK       KSI        fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
