$ Material Type 51
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      51              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat51                                                                   
$#       E     BLANK        NU                                   BLANK     ALPHA
        0.                  0.                                                  
$blank

$blank

$blank

$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
