$ Material Type 52 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      52              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat52                                                                   
$#       G    SIGMAy        Et     ALPHA     BLANK     BLANK    STRAT1    STRAT2
        0.CURVE             0.                                      0.        0.
$#       K        Ks        Nf        Lc
        0.        0.                    
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$# DUDATYP   SHDATYP                                   BLANK       KSI        Fo
                                                                    0.        0.
$#  STRAT3    STRAT4    STRAT5    STRAT6        Q1        Q2        Q3
        0.        0.        0.        0.        0.        0.        0.
$#    LCd1      LCd2      LCd3      LCd4      LCd5      LCd6      LCd7      LCd8
         0         0         0         0         0         0         0         0
$#   ERAd1     ERAd2     ERAd3     ERAd4     ERAd5     ERAd6     ERAd7     ERAd8
        0.        0.        0.        0.        0.        0.        0.        0.
$#    LCs1      LCs2      LCs3      LCs4      LCs5      LCs6      LCs7      LCs8
         0         0         0         0         0         0         0         0
$#   ERAs1     ERAs2     ERAs3     ERAs4     ERAs5     ERAs6     ERAs7     ERAs8
        0.        0.        0.        0.        0.        0.        0.        0.
