$  Material Type 6
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1       6              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat6                                                                    
$#       A         B        R1        R2     OMEGA
                                                  
$#       D       PCJ        E0
                              


$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
