$ Material Type 61
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      61              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat61                                                                   
$#       E     BLANK        NU                                   BLANK        As
        0.                  0.                                                  
$blank

$blank

$blank

$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$blank

