$  Material Type 7
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1       7              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat7                                                                    
$#       G    SIGMAy        Et       Pfr        E0
        0.        0.        0.        0.        0.
$#      C0        C1        C2        C3        C4        C5        C6
                                                                      
$#   EPSI1     EPSI2     EPSI3     EPSI4     EPSI5
        0.        0.        0.        0.        0.
$#   EPSI6     EPSI7     EPSI9    EPSI10
        0.        0.        0.        0.
$#  SIGMA1    SIGMA2    SIGMA3    SIGMA4    SIGMA5     BLANK       KSI        Fo
        0.        0.        0.        0.        0.                  0.        0.
$#  SIGMA6    SIGMA7    SIGMA8    SIGMA9        Q1        Q2        Q3
        0.        0.        0.        0.        0.        0.        0.
