$ Material Type 71 (CURVE Definition)
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      71              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat71                                                                   
$#       G    SIGMAy        Et     ALPHA     BLANK     BLANK    STRAT1    STRAT2
        0.CURVE             0.                                      0.        0.
$#       K        Dc        Rc      Plim   ALPHA_P      BETA
        0.                                                  
$#     LC1       LC2       LC3       LC4       LC5       LC6       LC7       LC8
         0         0         0         0         0         0         0         0
$#  ERATE1    ERATE2    ERATE3    ERATE4    ERATE5    ERATE6    ERATE7    ERATE8
        0.        0.        0.        0.        0.        0.        0.        0.
$#EPSIpmax     DEWKi     DEWK1        d1     DEWKu        du       KSI        Fo
                                                                    0.        0.
$#  STRAT3    STRAT4    STRAT5    STRAT6        Q1        Q2        Q3
        0.        0.        0.        0.        0.        0.        0.
