$  Material Type 8
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1       8              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat8                                                                    
$#       G    SIGMA0      BETA         n    GAMMAi        E0
        0.                                                  
$#IGMApmax         b        b'         B         f
                                                  
$#       A       Tm0      GAMA         a      Pcut         R
                                                0.          
$#      C0        C1        C2        C3        C4        C5        C6
                                                                      
$#                                                     BLANK       KSI        Fo
                                                                    0.        0.
$#                                 BLANK        Q1        Q2        Q3
                                                0.        0.        0.
