$ Material Type 99
$#         IDMAT   MATYP             RHO   ISINT    ISHG  ISTRAT   IFROZ
MATER /        1      99              0.       0       0                
$# BLANK                                                     QVM           IDMPD
                                                              1.               0
$#                                                                         TITLE
NAME 1=>mat99                                                                   
$#       E        NU
        0.        0.
$blank

$blank

$blank

$blank

$blank

