$VA Material Type 1
$#         IDMAT VAMATYP                                                   BLANK
VAMAT /        1       1                                                        
$#                                                                         BLANK
                                                                                
$#                                                                         TITLE
NAME 1=>VAMAT1_id1                                                              
$#   RHOFL    CELEFL     ETAFL
        0.        0.        0.
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
END_VAMAT
