$VA Material Type 2
$#         IDMAT VAMATYP                                                   BLANK
VAMAT /        1       2                                                        
$#                                                                         BLANK
                                                                                
$#                                                                         TITLE
NAME 1=>VAMAT2_id1                                                              
$#   RHOFL    CELEFL     ETAFL
        0.        0.        0.
$#   LVISC    LTHERM      PORO      RESI      TORT
        0.        0.        0.        0.        0.
$#   RHOST        NU     IFUN1     SCAL1     YOUNG     IFUN2     SCAL2     ETAST
        0.        0.         0        0.        0.         0        0.        0.
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
END_VAMAT
