$VA Material Type 3
$#         IDMAT VAMATYP                                                   BLANK
VAMAT /        1       3                                                        
$#                                                                         BLANK
                                                                                
$#                                                                         TITLE
NAME 1=>VAMAT3_id1                                                              
$#   RHOFL    CELEFL     ETAFL
        0.        0.        0.
$#   LVISC    LTHERM      PORO      RESI      TORT
        0.        0.        0.        0.        0.
$#   RHOST
        0.
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
END_VAMAT
