$VA Material Type 4
$#         IDMAT VAMATYP                                                   BLANK
VAMAT /        1       4                                                        
$#                                                                         BLANK
                                                                                
$#                                                                         TITLE
NAME 1=>VAMAT4_id1                                                              
$#   RHOST        NU     IFUN1     SCAL1     YOUNG     IFUN2     SCAL2     ETAST
        0.        0.         0        0.        0.         0        0.        0.
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
END_VAMAT
