$VA Material Type 5
$#         IDMAT VAMATYP                                                   BLANK
VAMAT /        1       5                                                        
$#                                                                         BLANK
                                                                                
$#                                                                         TITLE
NAME 1=>VAMAT5_id1                                                              
$#   RHOST
        0.
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
$#                                                                         BLANK
                                                                                
END_VAMAT
