$PFMAT Porous Material
$#         IDMAT
PFMAT /        1
$#                                                                         TITLE
NAME PFMAT->1                                                                   
$#       PORO
POROSITY   0.
$#        VISCO
VISCOSITY    0.
$#            QUALIFY Kxx Kyy Kzz Kxy Kxz Kyz
PERMEABILITY CONSTANT  0.  0.  0.  0.  0.  0.
$#            BETAxx BETAyy BETAzz BETAxy BETAxz BETAyz
VELOCITY_COEF     0.     0.     0.     0.     0.     0.
$#           Ru
GAS_CONSTANT 0.
$#                 TEMPgas
GAS_TEMPERATURE         0.
END_PFMAT  
