$THMAT Thermal Material
$#         IDMAT
THMAT /        1
$#                                                                         TITLE
NAME THMAT->1                                                                   
$#           QUALIFIER
MASS_DENSITY  CONSTANT 
$#     RHO
        0.
$#           QUALIFIER1 QUALIFIER2
CONDUCTIVITY  ISOTROPIC   CONSTANT 
$#      Kp
        0.
$#            QUALIFY_S
SPECIFIC_HEAT  CONSTANT 
$#      CP      Href
        0.        0.
$#          Qlat Tmin Tmax
LATENT_HEAT   0.   0.   0. 
$#       IFUNHT
ENTHALPY      0 
END_THMAT  
