$PLY Material Card
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       0              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#    Et11      Et22      Et33
        0.        0.        0.
$#    Gt12      Gt23      Gt13     NUt12     NUt23     NUt13
        0.        0.        0.        0.        0.        0.
$#EPSImtsi  EPSImts1  EPSImtsu     Dmts1     Dmtsu   IFUNmts
        0.        0.        0.        0.        0.         0
$#EPSImtvi  EPSImtv1  EPSImtvu     Dmtv1     Dmtvu   IFUNmtv
        0.        0.        0.        0.        0.         0
$#     Eft   ALPHAft   EPSIfti   EPSIft1   EPSIftu      Dft1      Dftu    IFUNft
        0.        0.        0.        0.        0.        0.        0.         0
$# KAPPA23   KAPPA13    ALPHA1    ALPHA2    ALPHA3
                                                  
$#    Ec11      Ec22      Ec33
        0.        0.        0.
$#    Gc12      Gc23      Gc13     NUc12     NUc23     NUc13
        0.        0.        0.        0.        0.        0.
$#EPSImcsi  EPSImcs1  EPSImcsu     Dmcs1     Dmcsu   IFUNmcs
        0.        0.        0.        0.        0.         0
$#EPSImcvi  EPSImcv1  EPSImcvu     Dmcv1     Dmcvu   IFUNmcv
        0.        0.        0.        0.        0.         0
$#     Efc   ALPHAfc   ALPHAfi   ALPHAf1   ALPHAfu      Dfc1      Dfcu    IFUNfc
        0.        0.        0.        0.        0.        0.        0.         0
