$PLY Type 1
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       1              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#    E0t1      E0t2
        0.        0.
$#    G012      G023      G013      NU12   KAPPA23   KAPPA13      ISHD      ITRD
        0.        0.        0.        0.        0.        0.                    
$#      Yc        Y0       Ycp       Y0p         b       Ysp        Yr      Dmax
        0.        0.        0.        0.        0.        0.        0.        0.
$# EPSIfti   EPSIftu      Dftu     Dsat1     Dsat2     Ycpc       Y0pc      Yspc
        0.        0.        0.                                                  
$#  IFUNd1    IFUNd2   IFUNd2c    Dsat2c
                                        
$#  ALPHA1    ALPHA2
                    
$#    E0c1     GAMMA   EPSIfci   EPSIfcu      Dfcu     IBUCK
        0.        0.        0.        0.        0.          
$#      R0      BETA         m         A
        0.        0.        0.        0.
$#ERATEr11       D11       n11      D11r      n1LAWTYP11
                                                        
$#ERATEr12       D22       n22       D12       nLAWTYP12
                                                        
$#ERATErR0       DR0       nLAWTYPR0
                                    
