$PLY Type 2
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       2              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#       E    SIGMAy        NU     BLANK                                      As
        0.                  0.                                                  
$#      E1    SIGMA1        E2    SIGMA2        E3    SIGMA3        E4    SIGMA4
        0.        0.        0.        0.        0.        0.        0.        0.
$#      E5    SIGMA5        E6    SIGMA6        E7    SIGMA7
        0.        0.        0.        0.        0.        0.
$#   BLANK    STRAT1    STRAT2     ESPIi     ESPI1        D1     ESPIu        Du
                  0.        0.        0.        0.        0.        0.        0.
$#   BLANK     BLANK    STRAT3    STRAT4    STRAT5    STRAT6
                            0.        0.        0.        0.
$blank

$blank

$blank

$blank

$blank

$blank

