$PLY Type 4
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       4              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#       E    SIGMAy        NU     BLANK     BLANK     BLANK     BLANK        As
        0.                  0.                                                  
$#      E1    SIGMA1        E2    SIGMA2        E3    SIGMA3        E4    SIGMA4
        0.        0.        0.        0.        0.        0.        0.        0.
$#      E5    SIGMA5        E6    SIGMA6        E7    SIGMA7
        0.        0.        0.        0.        0.        0.
$#   BLANK    STRAT1    STRAT2     BLANK     BLANK     QLANK     ILANK
                  0.        0.                                        
$#  STRAT3    STRAT4    STRAT5    STRAT6
        0.        0.        0.        0.
$#   ALPHA      BETA     GAMMA                         BLANK         M     BLANK
                                                                                





