$PLY Type 5
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       5              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#       A         B     BLANK
                              
$#     LTC
         0









