$PLY Type 6
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       6              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#    Et11      Et22      Et33
        0.        0.        0.
$#    Gt12      Gt23      Gt13     NUt12     NUt23     NUt13
        0.        0.        0.        0.        0.        0.
$# EPSItsi   EPSIts1   EPSItsu      Dts1      Dtsu
        0.        0.        0.        0.        0.
$# EPSItvi   EPSItv1   EPSItvu      Dtv1      Dtvu
        0.        0.        0.        0.        0.
$#    Eft1  ALPHAft1  EPSIfti1  EPSIft11  EPSIftu1     Dft11     Dftu1
        0.        0.        0.        0.        0.        0.        0.
$#    Eft2  ALPHAft2  EPSIfti2  EPSIft12  EPSIftu2     Dft12     Dftu2    ALPHA2
        0.        0.        0.        0.        0.        0.        0.          

$#    Ec11      Ec22      Ec33
        0.        0.        0.
$#    Gc12      Gc23      Gc13     NUc12     NUc23     NUc13
        0.        0.        0.        0.        0.        0.
$# EPSIcsi   EPSIcs1   EPSIcsu      Dcs1      Dcsu
        0.        0.        0.        0.        0.
$# EPSIcvi   EPSIcv1   EPSIcvu      Dcv1      Dcvu
        0.        0.        0.        0.        0.
$#    Efc1  ALPHAfc1  EPSIfci1  EPSIfc11  EPSIfcu1     Dfc11     Dfcu1
        0.        0.        0.        0.        0.        0.        0.
$#    Efc2  ALPHAfc2  EPSIfci2  EPSIfc12  EPSIfcu2     Dfc12     Dfcu2
        0.        0.        0.        0.        0.        0.        0.
