$PLY Type 7
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       7              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#     E01       E02
        0.        0.
$#    G012      G023      G013     NU012   KAPPA23   KAPPA13
        0.        0.        0.        0.        0.        0.
$#    Y12c      Y120      Y12R    D12max      Y11C      Y110      Y11R    D11max
        0.                            0.                                        


$#  ALPHA1    ALPHA2
                    
$#    E0c1      E0c2    NU0c12     Y11cC     Y11c0     Y11cR   D11cmax
        0.                                                            
$#      R0      BETA         m
        0.        0.        0.
$#ERATEr11       D11       n11  LAWTYP11 ERATErc11      D11c      n11c LAWTYP11c
                                                                                
$#ERATEr12       D12       n12  LAWTYP12
                                        
$#ERATErR0       DR0       nR0  LAWTYPR0
                                        
