$PLY Type 8
$#         IDPLY    ITYP             RHIFAIL_INP  ISTRAT             KSI
PLY   /        1       8              0.       0                        
$#                                                                         TITLE
NAME PLY   / ->1                                                                
$#    Et11      Et22      Et33
        0.        0.        0.
$#    Gt12      Gt23      Gt13     NUt12     NUt23     NUt13
        0.        0.        0.        0.        0.        0.
$#EPSImtsi  EPSImts1  EPSImtsu     Dmts1     Dmtsu   IFUNmts
        0.        0.        0.        0.        0.         0
$#EPSImtvi  EPSImtv1  EPSImtvu     Dmtv1     Dmtvu   IFUNmtv
        0.        0.        0.        0.        0.         0
$#    Eft1   GAMMAt1  EPSIft1i  EPSIft11  EPSIft1u     Dft11     Dft1u   IFUNft1
        0.                  0.        0.        0.        0.        0.         0
$#    Eft2   GAMMAt2  EPSIft2i  EPSIft21  EPSIft2u     Dft21     Dft2u   IFUNft2
        0.                  0.        0.        0.        0.        0.         0
$#      As      ANG2    VOLRf1    VOLRf2    IDAMCR     IWARP    ALPHA1    ALPHA2
                                                                                
$#    Ec11      Ec22      Ec33
        0.        0.        0.
$#    Gc12      Gc23      Gc13     NUc12     NUc23     NUc13
        0.        0.        0.        0.        0.        0.
$#EPSImcsi  EPSImcs1  EPSImcsu     Dmcs1     Dmcsu   IFUNmcs
        0.        0.        0.        0.        0.         0
$#EPSImcvi  EPSImcv1  EPSImcvu     Dmcv1     Dmcvu   IFUNmcv
        0.        0.        0.        0.        0.         0
$#    Efc1   GAMMAc1  EPSIfc1i  EPSIfc11  EPSIfc1u     Dfc11     Dfc1u   IFUNfc1
        0.                  0.        0.        0.        0.        0.         0
$#    Efc2   GAMMAc2  EPSIfc2i  EPSIfc21  EPSIfc2u     Dfc21     Dfc2u   IFUNfc2
        0.                  0.        0.        0.        0.        0.         0
