$Contact Type 10
$#         IDCTC   NTYPE
CNTAC /        1      10
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS NACCBLANK     EDGLN     Hcmin
        0.        0.         0    0             0.        0.
$#  SLFACM     FSVNL                                                      TLSTIF
        0.        0.                                                            
#blank

#blank

#blank

#blank

        END
