$contact Type 154
$#         IDCTC   NTYPE
CNTAC /        1     154
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#                       BLANK     HcontITPRT IORI
                                      0.          
$#PCP    SLFACM     FSVNL
             0.        0.
$#   FRICT                                          IDCNTPTY
        0.                                                  
$#RMV     BLANKIAC32                         BLANK    ADJTOL
    0              0                                        

$#                                                BLANK   SDISini   TshadowIPRES
                                                                                
        END
        END
