$Contact Type 21
$#         IDCTC   NTYPE
CNTAC /        1      21
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS      IMODIHYST IPEN INFI
        0.        0.         0STRESS             0     
$#IFUNFsdD                        DEPREF
         0                              
$#  IFUNCd         C
         0          
$# IFUNMUd        MU        V1        V2
         0        0.        0.        0.
$blank

$blank

        END
        END
