$Contact Type 34
$#         IDCTC   NTYPE
CNTAC /        1      34
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT                    IEDGE
        0.        0.         0        0.                             0
$#PCP    SLFACM     FSVNLIKFOR    PENKIN                                  TLSTIF
             0.        0.    0        0.                                        
$#   FRICT    IDFRIC     XDMP1              ICOUFR  IDCNTPTY
        0.         0        0.                              
$#RMVIERODILEAKIAC32               IFRED   DTHKPLK    ADJTOL
    0         0    0                                        
$#   BLANK    SEPSTR    SEPTHK
                              
$#                                      BLANK                              IPRES
                                                                                
        END
        END
