$Contact Type 36
$#         IDCTC   NTYPE
CNTAC /        1      36
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT                    IEDGE
        0.        0.         0        0.                             0
$#PCP    SLFACM     FSVNL                                                 TLSTIF
             0.        0.                                                       
$#   FRICT    IDFRIC     XDMP1              ICOUFR
        0.         0        0.                    
$#RMVIERODILEAKIAC32          IOMITIFRED   DTHKPLK    ADJTOL
    0         0    0                                        

$#                                      BLANK                              IPRES
                                                                                
        END
