$Contact Type 37
$#         IDCTC   NTYPE
CNTAC /        1      37
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT                   NINSEC
        0.        0.         0        0.                             0
$#ANK    SLFACM     FSVNLBLANK    PENKIN                                  TLSTIF
             0.        0.             0.                                        
$#   FRICT               XDMP1     BLANK    ICOUFR
        0.                  0.                    
$#EAKBLANK IRMV          BLANKIOMITIFRED
    0         0                         

$#                                                                    BLANKIPRES
                                                                                
        END
