$Contact Type 43
$#         IDCTC   NTYPE
CNTAC /        1      43
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT
        0.        0.         0        0.     
$#ANK    SLFACM     FSVNL                                        BLANK    TLSTIF
             0.        0.                                                       
$#   FRICT               XDMP1     BLANK    ICOUFR
        0.                  0.                    
$#   BLANK IRMV               BLANKIFRED
              0                         

$#                                                                    BLANKIPRES
                                                                                
        END
        END
