#Contact Type 44
$#         IDCTC   NTYPE
CNTAC /        1      44
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     Hcont
        0.        0.         0        0.
$#PCP    SLFACM     FSVNL                                                 TLSTIF
             0.        0.                                                       
$#   FRICT    IDFRIC     XDMP1     XDMPT
        0.         0        0.        0.
$#RMVBLANKILEAKBLANK    ITHKSV
    0         0              0

$#                                                                    BLANKIPRES
                                                                                
        END
        END
