$Contact Type 54
$#         IDCTC   NTYPE
CNTAC /        1      54
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#    T1SL      T2SL     ISENS     HcontITPRT IORI               IEDGE
        0.        0.         0        0.                             0
$#PCP    SLFACM     FSVNL                                                 TLSTIF
             0.        0.                                                       
$#   FRICT    IDFRIC     XDMP1              ICOUFR  IDCNTPTY
        0.         0        0.                              
$#RMV     ILEAKIAC32               IFRED              ADJTOL
    0         0    0                                        

$#                                      BLANK                       TshadowIPRES
                                                                                
        END
        END
