$Contact Type 61
$#         IDCTC   NTYPE
CNTAC /        1      61
$#                                                                         TITLE
NAME CNTAC / ->1                                                                
$#   MASTG    IDNODC     RADCS      IFRA      SOLU
                   0        0.         0          
$#ANK    SLFACM
             0.

$#RMV                                                 ADJTOL
    0                                                       

$#                                                                    BLANKIPRES
                                                                                
        END
