$MUSC1 Muscle Element Definition
$#         IDMUS    Fmax     ALF
MUSC1 /        1      0.        
$#                                                                         TITLE
NAME MUSC1 / ->1                                                                
$# BLANK    NLENNLEN_FAC   ALopt     CSH
               0                        
$# BLANK    NVELNVEL_FAC   AVmax  CSHORT   CLENG    CMVL
               0                                        
$# BLANK    NACTNACT_FAC    Tact  Tdeact   Texci    TREF   Ainit   Einit
               0                                                        
$# BLANK    NPASNPAS_FAC   L0fib   PEmax     CPE   CDAMP
               0                                        
$# BLANK   ITRIG  ELTRIG    WMAS    NMCY
                                        
        END
