$RETRA Belt Retractor Definition
$#         IDRET   IDNOD  FRETRA  FRCOUT   FRCIN   BLANK    NBW2
RETRA /        1       0      0.      0.      0.                
$#                                                                         TITLE
NAME RETRA / ->1                                                                
$# BLANK  ISENSR  ISPOOL  ISENSP  IREELR  IREELC ICURFRC
               0       0       0       0       0       0
        END
        END
