$PFSURF Porous Flow Exchange Surface
$#      PFSURFID
PFSURF/        1        
$#                                                                         TITLE
NAME PFSURF->1                                                                  
$#          QUALIFIER  AMBP
EXT_PRESSURE CONSTANT     0.
$#           FLOWTYP   QUALIFIER   VALUE  PRESSindex  POROindex
SURFACE_PERMEABILITY    CONSTANT       0.          0          0
$          SWITCH
OBSTRUCTION    NO
        END
