$TURBL Turbulent Boundary Layer Load
$#       IDTURBL   MODEL
TURBL /        1        
$#                                                                         TITLE
NAME TURBL->1                                                                   
$#FUNpsd SFACpsd     PSD
       0      0.      0.
$#  IDIR    IFRA    THCK  IFUNuc  SFACuc      UC
               0      0.       0      0.      0.
$#IFUNc1  SFACc1      C1  IFUNc2  SFACc2      C2
       0      0.      0.       0      0.      0.
        END
