$SENPT Sensor Point (Local)
$#         IDSPTIDNODref   RDIST    IFRA  IDNOD1  IDNOD2   ACFLG  IDAFLD
SENPT /        1       0      0.       0       0       0                
$#                                                                         TITLE
NAME SENPT / ->1                                                                
$# BLANK    MASS      Ix      Iy      Iz
              0.      0.      0.      0.
        END
