$PART Type BAR
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1     BAR       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#       A
          
$#      
END_PART
