$PART Type BEAM
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1    BEAM       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#       A      Ashs        Is        It        Ir      ITPR      Asht
                                                           0          
$#     Ist      COGs      COGt    RT1RR1    RT2RR2
                                                  
$#  ALPHA1     BETA1    GAMMA1      KSI1      ETA1
                                                  
$#  ALPHA2     BETA2    GAMMA2      KSI2      ETA2
                                                  
$#SEC NIPS
    0    0
$#      
END_PART
