$PART Type COS3D
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1   COS3D       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#   Blank       THK     XDIR1     YDIR1     ZDIR1     IMETH
                                                            
$#      
END_PART
