$PART Type PLINK
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1   PLINK       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#   RSEAR     NLAYR     SPWLG     NGESP    SPOTRA     THETA   IRADBEN    PHYRAD
                                                                                
$#      
END_PART
