$PART Type MEMBR
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1   MEMBR       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#       H     NDOFs
                    
$#RT1            VX1       VY1       VZ1   ALPHof1       TX1       TY1       TZ1
                                                                                
$#RT2            VX2       VY2       VZ2   ALPHof2       TX2       TY2       TZ2
                                                                                
$#      
END_PART
