#MPART Type SOLID
$#        IDMPRT   ATYPE
MPART /        1   SOLID
$#                                                                         TITLE
NAME MPART_1                                                                    
$#  IDMMAT  IDNUMPAR
         0         0
GEOMETRY
$#   IORT1     XDIR1     YDIR1     ZDIR1
                                        
$#   IORT2     XDIR2     YDIR2     ZDIR2
                                        
END_GEOMETRY
END_MPART
