#MPART Type SHELL
$#        IDMPRT   ATYPE
MPART /        1   SHELL
$#                                                                         TITLE
NAME MPART_1                                                                    
$#  IDMMAT  IDNUMPAR
         0         0
GEOMETRY
$#       H
          
$#    IORT      XDIR      YDIR      ZDIR
         0                              
END_GEOMETRY
END_MPART
