$PART Type SHELL
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1   SHELL       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#       H NINT    OFFSETNTDOF
              5               
$#ORTBLANK      XDIR      YDIR      ZDIR
    0                                   
$#      
END_PART
