$PART Type SOLID
$#         IDPRT   ATYPE   IDMAT IDVAMAT IDTHMAT  IDPMAT
PART  /        1   SOLID       0       0       0       0
$#                                                                         TITLE
NAME PART_1                                                                     
$#  DTELIM    TSCALF   DTRATIO
                              
$#   TCONT    EPSINI  COULFRIC
                              
$#RT1          XDIR1     YDIR1     ZDIR1
                                        
$#RT2          XDIR2     YDIR2     ZDIR2
                                        
$#      
END_PART
