$Gratitational Acceleration
ACFLD /       20       0      1.       0      1.      20     -1.       0
NAME Erdbeschleunigungsfeld
        NOD        1:99999999
        END
#---5---10----5---20----5---30----5---40----5---50----5---60----5---70----5---80
#          IDFUN    NPTS   SCALX   SCALY  SHIFTX  SHIFTY IFLMEAS   ICOMP
FUNCT /       20       2      1.   0.001      0.      0.       0       0
NAME Erdbeschleunigung
                              0.            9.81
                           1000.            9.81
