$MSTRM Mass Trimming
$#                    Mc             Ixc             Iyc             Izc
MSTRM /                                                                 
$# BLANK              Xc              Yc              Zc
                                                        
$# BLANK     EPS    ALFA    IFLG    IOUT  IDOFST
                                                
$#                                                                         TITLE
NAME MSTRM -> 1
        END
