$TRSFM Transformation Card
TRSFM / 
$#                                                                         TITLE
NAME TRSFM / ->1                                                                
        END
        MOVE     0. 0. 0. 0.       0       0
        ROTA       0.       0 0. 0. 0.       0       0
        SCAL      0    0.    0.    0.
        NPOS       0       0       0       0       0       0      0.
        END
